name: stdlib
adopt-info: stdlib
summary: Fortran Standard Library
description: |
  The Fortran Standard, as published by the ISO (https://wg5-fortran.org/), does not have a 
  Standard Library. The goal of this project is to provide a community driven and agreed upon 
  de facto "standard" library for Fortran, called a Fortran Standard Library (stdlib). We have a   
  rigorous process how stdlib is developed as documented in our Workflow. stdlib is both a
  specification and a reference implementation. We are cooperating with the Fortran Standards 
  Committee (e.g., the effort started at the J3 committee repository) and the plan is to continue
  working with the Committee in the future (such as in the step 5. in the Workflow document), 
  so that if the Committee wants to standardize some feature already available in stdlib, 
  it would base it on stdlib's implementation.
  
license: MIT
source-code: https://github.com/fortran-lang/stdlib
issues: https://github.com/kz6fittycent/stdlib/issues
contact: https://github.com/kz6fittycent/stdlib
icon: snap/local/stdlib.png
base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  s390x: 
    build-on: [s390x]
    build-for: [s390x]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]

parts:
  fypp:
    source: https://github.com/aradi/fypp
    source-type: git
    plugin: python
    python-packages:
      - fypp 
 
  stdlib:
    source: https://github.com/fortran-lang/stdlib
    source-type: git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr/local/stdlib
      - -DCMAKE_Fortran_COMPILER=/usr/bin/gfortran-10
    after:
      - fypp
    
    build-packages:
      - gfortran-10
      - ninja-build
      
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 

